class ReportAgent:

    def generate_report(self, content):
        return f"""
{content}
This report is automatically generated by UrbanBot, a Smart City AI Assistant.
---------------------
Generated by AI
"""